### ISSUE TITLE
Crash because log_domain is NULL.

### ISSUE THREAD

**Issue by chengchangwu** [gtk-rs/gtk-rs#28]
It seems `gst_video_info_from_caps` may generate a null `log_domain` because `G_LOG_DOMAIN` is not defined while building gst-plugins-base. I'm using gstreamer 1.16.

[crash-because-of-log-domain-null.log](https://github.com/gtk-rs/gtk-rs/files/5505918/crash-because-of-log-domain-null.log)

**Comment by chengchangwu** [comment]
I can make a PR, changing `log_domain` to a empty str or and "<unknown>" when `log_domain` is null. But I'm not sure it's the right way to do."

**Comment by sdroege** [comment]
See https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/634 but a `NULL` log domain is perfectly valid, see `glib/gmessages.h`:

```cpp
#ifndef G_LOG_DOMAIN
#define G_LOG_DOMAIN    ((gchar*) 0)
#endif  /* G_LOG_DOMAIN */
```

Can you create a PR that changes the API to work with an `Option` for the log domain (in all functions and the callback)?

For the stable release we should indeed map it to `"<null>"`. I'll fix that once the fix for git master is in.

**Comment by chengchangwu** [comment]
I'll try to make a PR to change the API.

**Comment by sdroege** [comment]
Great, thanks :) Let me know if you need help

**Comment by chengchangwu** [comment]
I'm trying to build a local version of gtk-rs and gstreamer-rs. For gstreamer-rs I have followed the instructions of gstreamer-rs/DEVELOPMENT. For gtk-rs I only do `python3 generator.py`。I've modified my application's Cargo.toml to use my local versions of gtk-rs and gstreamer. But the compilation failed with many errors. Any example of the error is,

```
error: no rules expected the token `,`
  --> /home/ccwu/git/rust/gstreamer-rs/gstreamer/src/auto/allocator.rs:11:82
   |
11 |     pub struct Allocator(Object<gst_sys::GstAllocator, gst_sys::GstAllocatorClass, AllocatorClass>) @extends Object;
   |                                                                                  ^ no rules expected this token in macro call
```

What I am missing? I've never build my local version of gtk-rs and gstreamer-rs before.

**Comment by sdroege** [comment]
Simply clone the `https://github.com/gtk-rs/gtk-rs` (not gtk-rs/gtk!) repository and then you can build it directly with `cargo` (to save yourself time, run `cargo build` etc inside the `glib subdirectory) and you can modify the code as needed.

`generator.py` is only needed to update the autogenerated code. The log handler is not autogenerated.

**Comment by chengchangwu** [comment]
> I'll try to make a PR to change the API.

**Comment by chengchangwu** [comment]
I've mistakenly closed the this thread. Do not know how to open it again.

Do you mean with changing the API to change the type of `log_domain` from `*const libc::c_char` to `Option<*const lib::c_char>`? Execuse me for such a newbie question. I found no Option<*const c_char> is used in glib.

**Comment by sdroege** [comment]
The interesting part is here https://github.com/gtk-rs/gtk-rs/blob/9561a784d1579b070fd2e59dc795567920c416cb/glib/src/log.rs#L117

The closure needs to take an `Option<&str>` instead of just `&str` for the first parameter.

The same here

https://github.com/gtk-rs/gtk-rs/blob/9561a784d1579b070fd2e59dc795567920c416cb/glib/src/log.rs#L244

and here

https://github.com/gtk-rs/gtk-rs/blob/9561a784d1579b070fd2e59dc795567920c416cb/glib/src/log.rs#L249

and here

https://github.com/gtk-rs/gtk-rs/blob/9561a784d1579b070fd2e59dc795567920c416cb/glib/src/log.rs#L287
