### ISSUE TITLE
Remove unused features in syn

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gtk-rs#41]
A lot of features in `syn` are enabled by default even though we don't use them. We should check which features we actually use and opt out all the others.

**Comment by pbor** [comment]
I opened https://github.com/gtk-rs/gtk-rs/pull/432 mostly for consistency.

I do not think there is much else we can do, since we depend from many other crates like `futures-macro` which also enable the `full` feature so even if we further customize the feature set, they would still get compiled:

https://github.com/rust-lang/futures-rs/blob/master/futures-macro/Cargo.toml

**Comment by sdroege** [comment]
Why do we depend on `futures-macro` (except for the tests via dev-dependencies)?

**Comment by bilelmoussaoui** [comment]
> Why do we depend on `futures-macro` (except for the tests via dev-dependencies)?

It comes from `futures-util` with the default `async-await-macro` feature. Do we need that one?

**Comment by sdroege** [comment]
No we don't. But why do we depend on `futures-util` still outside of `dev-dependencies` for the tests?

**Comment by bilelmoussaoui** [comment]
Aha, it comes from the default features of `futures-executor` https://github.com/rust-lang/futures-rs/blob/master/futures-executor/Cargo.toml#L16

**Comment by sdroege** [comment]
So should make that `default-features = false` too, but we also only use that from `dev-dependencies` too :)

**Comment by bilelmoussaoui** [comment]
It's used in https://github.com/gtk-rs/gtk-rs/blob/master/glib/src/main_context_futures.rs
